{% set name = "robotraconteur" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/robotraconteur/robotraconteur/archive/v{{ version }}.tar.gz
    sha256: 8bed280aafaca602e6d85247dbf102b18724746a7e79d73f332c6e908422dea8
  - url: http://www.kernel.org/pub/linux/bluetooth/bluez-5.56.tar.xz  # [linux]
    sha256: 59c4dba9fc8aae2a6a5f8f12f19bc1b0c2dc27355c7ca3123eed3fe6bd7d0b9d  # [linux]
    folder: bluez-src  # [linux]

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, min_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - ninja  # [win]    
    - make  # [linux]
    - git
    - cmake
    - swig
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - libboost-devel
    - python
    - pip
    - numpy
    - dbus  # [linux]
    - zlib  # [linux]
    - openssl  # [unix]
    - libusb  # [linux]
  run:
    - python
    - numpy

test:
  commands:
    - test -f ${PREFIX}/include/RobotRaconteur.h  # [not win]
    - if exist %PREFIX%\\Library\\include\\RobotRaconteur.h (exit 0) else (exit 1)  # [win]
    - test -f ${PREFIX}/lib/libRobotRaconteurCore${SHLIB_EXT}  # [not win]
    - if exist %PREFIX%\\Library\\lib\\RobotRaconteurCore.lib (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\RobotRaconteurCore.dll (exit 0) else (exit 1)  # [win]
    - python -c "from RobotRaconteur.Client import RRN; print(RRN.RobotRaconteurVersion)"

about:
  home: http://robotraconteur.com
  dev_url: https://github.com/robotraconteur/robotraconteur
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Communication framework for robotics and automation'

extra:
  recipe-maintainers:
    - traversaro
    - Tobias-Fischer
    - johnwason
